[workspace]
authors = ["chillenb <chillenbrand15@gmail.com>"]
channels = ["conda-forge"]
name = "chillenb-forge"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = ">=0.41.0,<0.42"
